spring.application.name=solr

solr.host=http://localhost:8983/solr
solr.connect-timeout=10000
solr.socket-timeout=60000

file.upload.dir=src/main/resources/data

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=3000

nvidia.api.key=${NVIDIA_API_KEY}
nvidia.api.url=https://integrate.api.nvidia.com/v1/chat/completions

